[package]
name = "amethyst"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/binary",
    "crates/raknet"
]

[dependencies]
bytes = "1.10.1"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
rand = "0.9.1"
tracing-subscriber = "0.3.19"

raknet = { version = "0.1.0", path = "crates/raknet" }
