[package]
name = "amethyst"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
bytes = "1.10.1"
uuid = { version = "1.6", features = ["serde", "v4"] }
tokio = { version = "1.44.2", features = ["full"]}
tracing = "0.1.41"