[package]
name = "raknet"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
bytes = "1.10.1"
binary = { version = "0.1.0", path = "../binary" }
tokio = { version = "1.44.2", features = ["full"] }
rand = "0.9.1"
tracing = "0.1.41"